name: Test and Build Wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest gym_super_mario_bros/tests/ -v --cov=gym_super_mario_bros --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-22.04  # Use single runner for universal wheels
    needs: test  # Only run if tests pass

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel setuptools-scm packaging

    - name: Build universal wheel
      run: |
        python -m build --wheel
        # Since this is a pure Python package, create universal wheel
        pip install wheel
        python setup.py bdist_wheel --universal || python -m build --wheel

    - name: Create wheelhouse directory
      run: |
        mkdir -p wheelhouse
        cp dist/*.whl wheelhouse/

    - uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_github_release:
    name: Upload to GitHub Release
    needs: [test, build_wheels, build_sdist]  # Include test dependency
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: write  # For uploading release assets
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist

    - uses: actions/download-artifact@v4
      with:
        name: cibw-sdist
        path: dist

    - name: Display structure of downloaded files
      run: find dist -type f -name "*.whl" -o -name "*.tar.gz"

    - name: Upload wheels to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Release ${{ github.ref_name }}
          
          ### 📦 Distribution Files
          This release includes wheel packages for:
          - **Universal**: Python 3.11+ (all platforms)
          - **Source**: Source distribution (.tar.gz)
          
          ### 🔧 Installation
          Download the appropriate wheel for your platform and Python version:
          ```bash
          pip install <downloaded-wheel-file>
          ```
          
          Or install from source:
          ```bash
          pip install <source-distribution-file>
          ```
          
          ### ✅ Quality Assurance
          All packages have been tested on Linux and Windows with Python 3.11 and 3.12.
        draft: false
        prerelease: false
