name: Test and Build Wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest gym_super_mario_bros/tests/ -v --cov=gym_super_mario_bros --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test  # Only run if tests pass
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.21.0
      env:
        CIBW_BUILD: cp311-* cp312-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
        CIBW_ARCHS_LINUX: x86_64
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_COMMAND: "python -c \"import gym_super_mario_bros; print('Package imported successfully')\""
        CIBW_TEST_REQUIRES: pytest
        CIBW_BEFORE_BUILD: "pip install setuptools>=77.0.0 packaging>=24.2"

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_github_release:
    name: Upload to GitHub Release
    needs: [test, build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-wheels-*
        path: dist
        merge-multiple: true

    - uses: actions/download-artifact@v4
      with:
        name: cibw-sdist
        path: dist

    - name: Display structure of downloaded files
      run: find dist -type f -name "*.whl" -o -name "*.tar.gz"

    - name: Upload wheels to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Release ${{ github.ref_name }}
          
          ### 📦 Distribution Files
          This release includes wheel packages for:
          - **Linux**: Python 3.11, 3.12 (x86_64)
          - **Windows**: Python 3.11, 3.12 (AMD64)
          - **Source**: Source distribution (.tar.gz)
          
          ### 🔧 Installation
          Download the appropriate wheel for your platform and Python version:
          ```bash
          pip install <downloaded-wheel-file>
          ```
          
          Or install from PyPI (if published):
          ```bash
          pip install gym-super-mario-bros
          ```
          
          ### ✅ Quality Assurance
          All packages have been tested on their respective platforms with Python 3.11 and 3.12.
        draft: false
        prerelease: false
