name: Test and Build Wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest gym_super_mario_bros/tests/ -v --cov=gym_super_mario_bros --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build_wheels:
    name: Build pure Python wheel
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel setuptools-scm packaging

    - name: Build pure Python wheel
      run: |
        python -m build --wheel

    - name: Test wheel installation
      run: |
        pip install dist/*.whl
        python -c "import gym_super_mario_bros; print('✅ Package imported successfully')"

    - name: Create wheelhouse directory and copy wheel
      run: |
        mkdir -p wheelhouse
        cp dist/*.whl wheelhouse/

    - uses: actions/upload-artifact@v4
      with:
        name: pure-python-wheel
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_github_release:
    name: Upload to GitHub Release
    needs: [test, build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: pure-python-wheel
        path: dist

    - uses: actions/download-artifact@v4
      with:
        name: cibw-sdist
        path: dist

    - name: Display structure of downloaded files
      run: find dist -type f -name "*.whl" -o -name "*.tar.gz"

    - name: Upload wheels to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Release ${{ github.ref_name }}
          
          ### 📦 Distribution Files
          This release includes:
          - **Pure Python Wheel**: Compatible with Python 3.11+ on all platforms (Linux, Windows, macOS)
          - **Source Distribution**: Source code (.tar.gz)
          
          ### 🔧 Installation
          Download and install the wheel:
          ```bash
          pip install <downloaded-wheel-file>
          ```
          
          Or install from PyPI (if published):
          ```bash
          pip install gym-super-mario-bros
          ```
          
          Or install from source:
          ```bash
          pip install <source-distribution-file>
          ```
          
          ### ✅ Quality Assurance
          The package has been tested on Linux and Windows with Python 3.11 and 3.12.
          
          ### 🎮 Usage
          ```python
          import gym_super_mario_bros
          from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
          
          env = gym_super_mario_bros.make('SuperMarioBros-v0')
          env = JoypadSpace(env, SIMPLE_MOVEMENT)
          ```
        draft: false
        prerelease: false
